require "numo/gnuplot"

require_relative "maxima/core"
require_relative "maxima/command"
require_relative "maxima/unit"
require_relative "maxima/function"
require_relative "maxima/histogram"
require_relative "maxima/polynomial"
require_relative "maxima/rational"
require_relative "maxima/complex"
require_relative "maxima/float"
require_relative "helper"
